# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hi! Thanks for opening your first issue here! Please make sure to follow the
  issue template - so we could help you better!

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Thanks for opening this pull request!

  We will try to review this soon! Please note that pull requests with unit
  tests are earlier accepted :angel:

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Hooray your first pull request is merged! Thanks for the contribution! Looking
  for more? :angel: Please check the [up-for-grabs
  issues](https://github.com/NLog/NLog/issues?q=is%3Aopen+is%3Aissue+label%3Aup-for-grabs)
  - thanks!

  ![thanks!](https://i.imgflip.com/1g17ph.jpg)

# Configuration for request-info - https://github.com/behaviorbot/request-info

# *OPTIONAL* Comment to reply with
# Can be either a string :
# requestInfoReplyComment: >
#   We would appreciate it if you could provide us with more info about this issue/pr!

# Or an array:
requestInfoReplyComment:
  - Ah no! young blade! That was a trifle short!
  - Tell me more !
  - I am sure you can be more effusive

# *OPTIONAL* default titles to check against for lack of descriptiveness
# MUST BE ALL LOWERCASE
requestInfoDefaultTitles:
  - update readme.md
  - updates
  - fix
  - fixes

# *OPTIONAL* Label to be added to Issues and Pull Requests with insufficient information given
requestInfoLabelToAdd: needs-more-info

# *OPTIONAL* Require Issues to contain more information than what is provided in the issue templates
# Will fail if the issue's body is equal to a provided template
checkIssueTemplate: true

# *OPTIONAL* Require Pull Requests to contain more information than what is provided in the PR template
# Will fail if the pull request's body is equal to the provided template
checkPullRequestTemplate: true

todo:
  keyword: '@makeAnIssue'
